language: csharp
solution: NLogInjector.sln

before_install:
  - sudo apt-get install nunit-console

install: 
  - nuget restore NLogInjector.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release NLogInjector.sln

after_script:
  - nunit-console NLogInjector.UnitTests/bin/Release/NLogInjector.UnitTests.dll