language: csharp
solution: NLogInjector.sln

install: 
  - nuget restore NLogInjector.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release NLogInjector.sln
  - mono ./testrunner/NUnit.Runners.3.2.0/tools/nunit-console.exe ./NLogInjector.UnitTests/bin/Release/NLogInjector.UnitTests.dll