version: 0.0.{build}
branches:
  only:
  - master
os:
  - Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
before_build: 
  - nuget restore NLogInjector.sln
after_build:
  - dotnet pack NLogInjector -p:PackageVersion=%appveyor_build_version% --output ..
  - appveyor PushArtifact NLogInjector.%appveyor_build_version%.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: x54x3OvPJQDpqP3HpyWLnqEW06HsThUeogaEKwJQDOV+PLmX0dKwbtyio5bumyt/
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/